### ISSUE TITLE
How can you tell which direction the planet is rotating?

### ISSUE THREAD

**Issue by kfogel** [lkreidberg/atmospheres-chapter#1]
Excuse me, Dr. Kriedberg, I have a question.  How can we tell which direction the planet is rotating, around its axis and around the star?  Is it harder or easier if the planet is tidally locked?

Thank you.

**Comment by lkreidberg** [comment]
you ask the aliens, duh!

**Comment by kfogel** [comment]
Oh.  I'm sorry -- I should have read the citations.
